import type{KmaPersistentCache}from"./kma-cache.ts";

const ENDPOINT="https://apihub.kma.go.kr/api/typ02/openApi/VilageFcstInfoService_2.0/getVilageFcst",ISSUE_HOURS=[2,5,8,11,14,17,20,23];
const l1=new Map<string,NormalizedForecast>(),inFlight=new Map<string,Promise<ForecastResult>>();
const stats={requestCount:0,successCount:0,failureCount:0,receivedBytes:0,cacheHit:0,cacheMiss:0,inFlightReuse:0,http429:0,http403:0,http5xx:0,timeout:0};
const numberOrNull=(value:unknown)=>value===null||value===undefined||value===""||!Number.isFinite(Number(value))?null:Number(value);
const envNumber=(name:string,fallback:number)=>{const value=Number(Deno.env.get(name));return Number.isFinite(value)&&value>=0?value:fallback};
export type NormalizedForecast={gridKey:string;nx:number;ny:number;baseDate:string;baseTime:string;fetchedAt:string;hourly:Array<Record<string,unknown>>;daily:Array<Record<string,unknown>>;rawMeta:{itemCount:number;receivedBytes:number};elapsedMs?:number};
export type ForecastResult=NormalizedForecast&{cacheStatus:"fresh"|"stale";cacheLevel:"l1"|"supabase"|"upstream";refreshError?:{code:string;status:number|null}};

function kstParts(date=new Date()){const parts=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Seoul",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(date);return Object.fromEntries(parts.map(part=>[part.type,part.value]))}
export function getLatestAvailableKmaBaseTime(now=new Date(),delayMinutes=envNumber("KMA_BASE_DELAY_MINUTES",40)){const p=kstParts(now),minutes=Number(p.hour)*60+Number(p.minute)-delayMinutes;let date=new Date(Date.UTC(Number(p.year),Number(p.month)-1,Number(p.day))),hour=ISSUE_HOURS.filter(value=>value*60<=minutes).at(-1);if(hour===undefined){date=new Date(date.getTime()-86400000);hour=23}return{baseDate:`${date.getUTCFullYear()}${String(date.getUTCMonth()+1).padStart(2,"0")}${String(date.getUTCDate()).padStart(2,"0")}`,baseTime:`${String(hour).padStart(2,"0")}00`}}
export function parseKmaPcp(value:unknown){const raw=value===null||value===undefined?null:String(value).trim();if(!raw)return{raw,mm:null,hasRain:null};if(raw==="강수없음"||raw==="0"||raw==="0.0")return{raw,mm:0,hasRain:false};if(/미만|~|이상/.test(raw))return{raw,mm:null,hasRain:true};const match=raw.match(/^([0-9]+(?:\.[0-9]+)?)\s*(?:mm)?$/i);if(!match)return{raw,mm:null,hasRain:null};const mm=Number(match[1]);return{raw,mm,hasRain:mm>0}}
export function normalizeKmaSky(value:unknown){const code=numberOrNull(value),labels:Record<number,string>={1:"맑음",3:"구름많음",4:"흐림"};return{code,label:code===null?null:labels[code]??null}}
export function normalizeKmaPty(value:unknown){const code=numberOrNull(value),labels:Record<number,string>={0:"없음",1:"비",2:"비/눈",3:"눈",4:"소나기",5:"빗방울",6:"빗방울/눈날림",7:"눈날림"};return{code,label:code===null?null:labels[code]??null}}
function enforceSoftLimits(){const requestLimit=envNumber("KMA_DAILY_REQUEST_SOFT_LIMIT",Infinity),byteLimit=envNumber("KMA_DAILY_BYTES_SOFT_LIMIT",Infinity);if(stats.requestCount>=requestLimit||stats.receivedBytes>=byteLimit)throw Object.assign(new Error("KMA soft limit reached"),{code:"SOFT_LIMIT"})}
function normalize(items:Array<Record<string,any>>,nx:number,ny:number,baseDate:string,baseTime:string,receivedBytes:number):NormalizedForecast{
  const hourly=new Map<string,Record<string,unknown>>(),daily=new Map<string,Record<string,unknown>>();
  for(const item of items){const date=String(item.fcstDate||""),time=String(item.fcstTime||"").padStart(4,"0"),datetime=`${date.slice(0,4)}-${date.slice(4,6)}-${date.slice(6,8)}T${time.slice(0,2)}:${time.slice(2,4)}:00+09:00`;
    if(item.category==="TMX"||item.category==="TMN"){if(!daily.has(date))daily.set(date,{date:`${date.slice(0,4)}-${date.slice(4,6)}-${date.slice(6,8)}`,tempMax:null,tempMin:null});daily.get(date)![item.category==="TMX"?"tempMax":"tempMin"]=numberOrNull(item.fcstValue);continue}
    if(!hourly.has(datetime))hourly.set(datetime,{datetime,temperature:null,windSpeed:null,windDirection:null,precipitation:null,precipitationProbability:null,sky:null,precipitationType:null});const row=hourly.get(datetime)!,value=item.fcstValue;
    if(item.category==="TMP")row.temperature=numberOrNull(value);else if(item.category==="WSD")row.windSpeed=numberOrNull(value);else if(item.category==="VEC")row.windDirection=numberOrNull(value);else if(item.category==="PCP")row.precipitation=parseKmaPcp(value);else if(item.category==="POP")row.precipitationProbability=numberOrNull(value);else if(item.category==="SKY")row.sky=normalizeKmaSky(value);else if(item.category==="PTY")row.precipitationType=normalizeKmaPty(value)}
  return{gridKey:`${nx}:${ny}`,nx,ny,baseDate,baseTime,fetchedAt:new Date().toISOString(),hourly:[...hourly.values()].sort((a,b)=>String(a.datetime).localeCompare(String(b.datetime))),daily:[...daily.values()].sort((a,b)=>String(a.date).localeCompare(String(b.date))),rawMeta:{itemCount:items.length,receivedBytes}}
}
export async function fetchKmaVillageForecast(nx:number,ny:number,baseDate:string,baseTime:string,fetchImpl=fetch){
  const key=Deno.env.get("KMA_API_KEY");if(!key)throw Object.assign(new Error("KMA_API_KEY is not configured"),{code:"CONFIG"});
  enforceSoftLimits();const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),envNumber("KMA_FETCH_TIMEOUT_MS",15000)),started=Date.now();stats.requestCount++;
  try{const url=new URL(ENDPOINT);for(const[name,value]of Object.entries({pageNo:1,numOfRows:1100,dataType:"JSON",base_date:baseDate,base_time:baseTime,nx,ny,authKey:key}))url.searchParams.set(name,String(value));const response=await fetchImpl(url,{signal:controller.signal,headers:{Accept:"application/json"}}),text=await response.text(),bytes=new TextEncoder().encode(text).byteLength;stats.receivedBytes+=bytes;if(!response.ok)throw Object.assign(new Error(`KMA HTTP ${response.status}`),{code:"HTTP",status:response.status});let payload;try{payload=JSON.parse(text)}catch{throw Object.assign(new Error("KMA JSON parsing failed"),{code:"PARSE"})}const header=payload?.response?.header;if(String(header?.resultCode)!=="00")throw Object.assign(new Error("KMA result error"),{code:"KMA_RESULT"});const items=payload?.response?.body?.items?.item;if(!Array.isArray(items))throw Object.assign(new Error("KMA forecast items are missing"),{code:"SHAPE"});stats.successCount++;return{...normalize(items,nx,ny,baseDate,baseTime,bytes),elapsedMs:Date.now()-started}}
  catch(error){const value=error as Error&{code?:string;status?:number};if(value.name==="AbortError"){value.code="TIMEOUT";stats.timeout++}if(value.status===429)stats.http429++;if(value.status===403)stats.http403++;if(value.status&&value.status>=500)stats.http5xx++;stats.failureCount++;throw value}finally{clearTimeout(timer)}
}
export async function getKmaForecast(cache:KmaPersistentCache,nx:number,ny:number,baseDate:string,baseTime:string,fetchImpl=fetch):Promise<ForecastResult>{
  const gridKey=`${nx}:${ny}`,key=`${gridKey}:${baseDate}:${baseTime}`;if(l1.has(key)){stats.cacheHit++;return{...l1.get(key)!,cacheStatus:"fresh",cacheLevel:"l1"}}stats.cacheMiss++;
  if(inFlight.has(key)){stats.inFlightReuse++;return inFlight.get(key)!}
  const promise=(async()=>{const stored=await cache.get(gridKey,baseDate,baseTime);if(stored){l1.set(key,stored);stats.cacheHit++;return{...stored,cacheStatus:"fresh",cacheLevel:"supabase"}as ForecastResult}try{const value=await fetchKmaVillageForecast(nx,ny,baseDate,baseTime,fetchImpl);await cache.upsert(value);l1.set(key,value);return{...value,cacheStatus:"fresh",cacheLevel:"upstream"}as ForecastResult}catch(error){const stale=await cache.getLatestSuccessful(gridKey);if(stale)return{...stale,cacheStatus:"stale",cacheLevel:"supabase",refreshError:{code:(error as any)?.code||"UNKNOWN",status:(error as any)?.status??null}}as ForecastResult;throw error}})().finally(()=>inFlight.delete(key));inFlight.set(key,promise);return promise;
}
export async function mapConcurrent<T,R>(items:T[],limit:number,task:(item:T)=>Promise<R>){let cursor=0;const results:PromiseSettledResult<R>[] = new Array(items.length);async function worker(){while(true){const index=cursor++;if(index>=items.length)return;try{results[index]={status:"fulfilled",value:await task(items[index])}}catch(reason){results[index]={status:"rejected",reason}}}}await Promise.all(Array.from({length:Math.min(limit,items.length)},worker));return results}
export const getKmaTrafficStats=()=>({...stats,l1Entries:l1.size,inFlight:inFlight.size});
export const clearKmaL1ForTest=()=>{l1.clear()};
