import{createClient,type SupabaseClient}from"npm:@supabase/supabase-js@2";

export const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type, x-refresh-secret","Access-Control-Allow-Methods":"GET, POST, OPTIONS"};
export const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}});
export function serviceClient():SupabaseClient{const url=Deno.env.get("SUPABASE_URL"),key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!key)throw new Error("Supabase server configuration unavailable");return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})}
export function authorizeRefresh(request:Request){const expected=Deno.env.get("KMA_REFRESH_SECRET"),actual=request.headers.get("x-refresh-secret")||request.headers.get("authorization")?.replace(/^Bearer\s+/i,"")||"";return Boolean(expected&&actual&&expected.length===actual.length&&[...expected].reduce((difference,char,index)=>difference|(char.charCodeAt(0)^actual.charCodeAt(index)),0)===0)}
export async function mappingKeys(client:SupabaseClient,column:string){const{data,error}=await client.from("point_marine_source_mapping").select(`point_id,${column}`).not(column,"is",null);if(error)throw error;return[...new Set((data||[]).map(row=>String(row[column]||"").trim()).filter(Boolean))]}
export async function concurrent<T,R>(values:T[],limit:number,worker:(value:T)=>Promise<R>){const output:PromiseSettledResult<R>[]=[];let cursor=0;async function run(){while(cursor<values.length){const index=cursor++;try{output[index]={status:"fulfilled",value:await worker(values[index])}}catch(reason){output[index]={status:"rejected",reason}}}await Promise.all(Array.from({length:Math.min(limit,values.length)},run));return output}
export const failure=(reason:unknown)=>({code:(reason as any)?.code||"UNKNOWN",status:(reason as any)?.status??null,message:reason instanceof Error?reason.message:"unknown"});
