import{createClient,type SupabaseClient}from"npm:@supabase/supabase-js@2";
const FIELDS=["wave_height","wave_period","ocean_current_velocity","sea_surface_temperature"];
const FETCH_MS=15000,DB_MS=12000,BATCH_SIZE=15,FRESH_MS=6*3600000,SOFT_HTTP_BUDGET=100,HARD_HTTP_BUDGET=200;
type Target={pointId:number;latitude:number;longitude:number;cacheKey:string};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}});
const coordinateKey=(lat:number,lon:number)=>`${lat.toFixed(4)}:${lon.toFixed(4)}`;
const timed=async<T>(promise:PromiseLike<T>,ms:number,code:string)=>{let timer:number|undefined;try{return await Promise.race([Promise.resolve(promise),new Promise<T>((_,reject)=>{timer=setTimeout(()=>reject(Object.assign(new Error(code),{code})),ms)})])}finally{if(timer)clearTimeout(timer)}};
const client=()=>{const url=Deno.env.get("SUPABASE_URL"),key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!key)throw new Error("Supabase server configuration unavailable");return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})};
const legacyAuthorized=(request:Request)=>{const expected=Deno.env.get("KMA_REFRESH_SECRET"),actual=request.headers.get("x-refresh-secret")||request.headers.get("authorization")?.replace(/^Bearer\s+/i,"")||"";return Boolean(expected&&actual&&expected.length===actual.length&&[...expected].reduce((d,c,i)=>d|(c.charCodeAt(0)^actual.charCodeAt(i)),0)===0)};
async function schedulerAuthorized(db:SupabaseClient,request:Request){const candidate=request.headers.get("x-scheduler-token")||"";if(!candidate)return false;const{data,error}=await db.rpc("validate_open_meteo_marine_scheduler_token",{candidate});return !error&&data===true}
const marineUrl=(lat:number[],lon:number[])=>{const url=new URL((Deno.env.get("OPEN_METEO_MARINE_BASE_URL")||"https://marine-api.open-meteo.com/v1/marine").replace(/\/$/,""));url.searchParams.set("latitude",lat.join(","));url.searchParams.set("longitude",lon.join(","));url.searchParams.set("hourly",FIELDS.join(","));url.searchParams.set("velocity_unit","ms");url.searchParams.set("timezone","Asia/Seoul");url.searchParams.set("past_days","2");url.searchParams.set("forecast_days","7");const key=Deno.env.get("OPEN_METEO_API_KEY");if(key)url.searchParams.set("apikey",key);return url};
const finite=(v:unknown)=>v===null||v===undefined||v===""?null:Number.isFinite(Number(v))?Number(v):null;
const normalize=(p:any)=>{const h=p?.hourly,t=Array.isArray(h?.time)?h.time:[],unit=String(p?.hourly_units?.ocean_current_velocity||"km/h").toLowerCase(),currentToMs=(value:any)=>{const current=finite(value);if(current===null)return null;if(unit==="km/h"||unit==="kmh"||unit==="kph")return current/3.6;if(unit==="mph")return current*.44704;if(unit==="kn"||unit==="knots")return current*.514444;return current};return t.map((forecastAt:string,i:number)=>({forecastAt,wave_height:finite(h.wave_height?.[i]),wave_period:finite(h.wave_period?.[i]),ocean_current_velocity:currentToMs(h.ocean_current_velocity?.[i]),sea_surface_temperature:finite(h.sea_surface_temperature?.[i])})).filter((r:any)=>Object.entries(r).some(([k,v])=>k!=="forecastAt"&&v!==null))};
async function usage(db:SupabaseClient){const date=new Date().toISOString().slice(0,10),{data,error}=await db.from("open_meteo_api_usage").select("*").eq("provider","open_meteo_marine").eq("usage_date",date).maybeSingle();if(error)throw error;return{date,row:data||{}}}
async function bumpUsage(db:SupabaseClient,delta:Record<string,number>,status?:number){const current=await usage(db),row:any={provider:"open_meteo_marine",usage_date:current.date,updated_at:new Date().toISOString()};for(const key of ["refresh_runs","http_requests","batch_requests","success_requests","count_429","count_5xx","timeout_count","request_count","batch_count"])row[key]=Number(current.row[key]||0)+Number(delta[key]||0);if(status!==undefined){row.last_http_status=status;row.last_request_at=new Date().toISOString()}const{error}=await db.from("open_meteo_api_usage").upsert(row,{onConflict:"provider,usage_date"});if(error)throw error;return row}
async function rateSnapshot(db:SupabaseClient,planned:number){const{data,error}=await db.rpc("open_meteo_rate_limit_snapshot",{p_planned:planned});if(error)throw error;return data as any}
async function startRequest(db:SupabaseClient,runId:string){const{data,error}=await db.from("open_meteo_api_request_log").insert({provider:"open_meteo_marine",run_id:runId,request_kind:"batch",outcome:"started"}).select("id").single();if(error)throw error;await bumpUsage(db,{http_requests:1,batch_requests:1,request_count:1,batch_count:1});return Number(data.id)}
async function completeRequest(db:SupabaseClient,id:number,status:number|null,outcome:string){await db.from("open_meteo_api_request_log").update({http_status:status,outcome,completed_at:new Date().toISOString()}).eq("id",id)}
async function writeTarget(db:SupabaseClient,target:Target,payload:any,bytes:number){const rows=normalize(payload);if(!rows.length)throw Object.assign(new Error("empty or invalid marine rows"),{code:"EMPTY_INVALID"});const issuedAt=new Date().toISOString(),records=rows.map((row:any)=>({cache_key:target.cacheKey,latitude:target.latitude,longitude:target.longitude,issued_at:issuedAt,forecast_at:row.forecastAt,normalized_data:row,source_payload_meta:{timezone:payload.timezone??null,utcOffsetSeconds:payload.utc_offset_seconds??null,generationTimeMs:payload.generationtime_ms??null},fetched_at:issuedAt,status:"fresh",stale:false,response_bytes:bytes,updated_at:issuedAt})),result=await timed(db.from("open_meteo_marine_cache").upsert(records,{onConflict:"cache_key,issued_at,forecast_at"}),DB_MS,"DB_WRITE_TIMEOUT");if((result as any).error)throw(result as any).error;return{pointId:target.pointId,cacheKey:target.cacheKey,itemCount:records.length}}
async function fetchBatch(db:SupabaseClient,runId:string,targets:Target[]){const requestId=await startRequest(db,runId),ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),FETCH_MS);let status=0;try{const response=await fetch(marineUrl(targets.map(x=>x.latitude),targets.map(x=>x.longitude)),{signal:ctl.signal,headers:{Accept:"application/json"}});status=response.status;await completeRequest(db,requestId,status,response.ok?"http_success":"http_failure");const text=await response.text(),bytes=new TextEncoder().encode(text).byteLength;if(status===429)throw Object.assign(new Error("rate limited"),{code:"MARINE_429",status});if(!response.ok)throw Object.assign(new Error(`HTTP ${status}`),{code:status>=500?"MARINE_5XX":"MARINE_HTTP",status});let parsed:any;try{parsed=JSON.parse(text)}catch{throw Object.assign(new Error("invalid JSON"),{code:"MARINE_INVALID",status})}const payloads=Array.isArray(parsed)?parsed:[parsed];if(payloads.length!==targets.length||payloads.some(p=>normalize(p).length===0))throw Object.assign(new Error("empty or invalid batch"),{code:"EMPTY_INVALID",status});return{status,bytes,payloads}}catch(error){if(ctl.signal.aborted){await completeRequest(db,requestId,null,"timeout");throw Object.assign(new Error("timeout"),{code:"MARINE_TIMEOUT",status})}throw error}finally{clearTimeout(timer)}}
Deno.serve(async request=>{
  if(request.method!=="POST")return json({ok:false,code:"METHOD_NOT_ALLOWED"},405);
  const db=client();if(!legacyAuthorized(request)&&!await schedulerAuthorized(db,request))return json({ok:false,code:"UNAUTHORIZED"},401);
  const owner=crypto.randomUUID();let locked=false;
  try{
    const lock=await db.rpc("acquire_open_meteo_marine_lease",{p_owner:owner,p_lease_seconds:600});if(lock.error)throw lock.error;if(lock.data!==true)return json({ok:true,externalCall:"SKIP",reason:"LOCKED"});locked=true;
    await bumpUsage(db,{refresh_runs:1});
    const points=await timed(db.from("points").select("id,lat,lng"),DB_MS,"DB_QUERY_TIMEOUT");if((points as any).error)throw(points as any).error;
    const targets=[...new Map(((points as any).data||[]).filter((r:any)=>Number.isFinite(Number(r.lat))&&Number.isFinite(Number(r.lng))).map((r:any)=>{const t={pointId:Number(r.id),latitude:Number(r.lat),longitude:Number(r.lng),cacheKey:coordinateKey(Number(r.lat),Number(r.lng))};return[t.cacheKey,t]})).values()] as Target[];
    const now=Date.now(),windowMs=6*3600000,anchorMs=30*60000,windowStart=Math.floor((now-anchorMs)/windowMs)*windowMs+anchorMs,cutoff=new Date(Math.max(now-FRESH_MS,windowStart)).toISOString(),freshResult=await db.from("open_meteo_marine_cache").select("cache_key").eq("status","fresh").eq("stale",false).gte("fetched_at",cutoff).in("cache_key",targets.map(x=>x.cacheKey)),fresh=new Set((freshResult.data||[]).map((x:any)=>x.cache_key));
    if(targets.length===57&&fresh.size===targets.length)return json({ok:true,externalCall:"SKIP",reason:"FRESH_FULL_COVERAGE",coverage:fresh.size,freshHours:6,windowStart:new Date(windowStart).toISOString()});
    let today=await usage(db);if(Number(today.row.http_requests||0)>=HARD_HTTP_BUDGET)return json({ok:true,externalCall:"SKIP",reason:"HARD_BUDGET",httpRequests:Number(today.row.http_requests||0),hardBudget:HARD_HTTP_BUDGET});
    const pending=targets.filter(x=>!fresh.has(x.cacheKey)),batches:Target[][]=[];for(let i=0;i<pending.length;i+=BATCH_SIZE)batches.push(pending.slice(i,i+BATCH_SIZE));const initialRate=await rateSnapshot(db,batches.length);if(initialRate?.safe!==true)return json({ok:true,externalCall:"SKIP",reason:"OFFICIAL_RATE_LIMIT_GUARD",rateLimit:initialRate});
    const results:any[]=[],failures:any[]=[];let requests=0,count429=0,count5xx=0,timeouts=0;
    for(let batchIndex=0;batchIndex<batches.length;batchIndex++){const batch=batches[batchIndex],remaining=batches.length-batchIndex,rate=await rateSnapshot(db,remaining);if(rate?.safe!==true){failures.push({code:"OFFICIAL_RATE_LIMIT_GUARD",rateLimit:rate});break}today=await usage(db);if(Number(today.row.http_requests||0)>=HARD_HTTP_BUDGET){failures.push({code:"HARD_BUDGET"});break}try{const outcome=await fetchBatch(db,owner,batch);requests++;await bumpUsage(db,{success_requests:1},outcome.status);for(let i=0;i<batch.length;i++)results.push(await writeTarget(db,batch[i],outcome.payloads[i],outcome.bytes))}catch(error){requests++;const code=(error as any)?.code||"UNKNOWN",status=Number((error as any)?.status||0),delta:any={};if(code==="MARINE_429"){delta.count_429=1;count429++}if(code==="MARINE_5XX"){delta.count_5xx=1;count5xx++}if(code==="MARINE_TIMEOUT"){delta.timeout_count=1;timeouts++}await bumpUsage(db,delta,status);failures.push({cacheKeys:batch.map(x=>x.cacheKey),code,status});if(code==="MARINE_429")break}}
    today=await usage(db);return json({ok:failures.length===0,externalCall:requests?"CALLED":"SKIP",activePoints:targets.length,coverageBefore:fresh.size,httpRequests:requests,batchRequests:requests,count429,count5xx,timeouts,cacheWrites:results.length,softBudgetExceeded:Number(today.row.http_requests||0)>=SOFT_HTTP_BUDGET,hardBudget:HARD_HTTP_BUDGET,failures})
  }catch(error){console.error("[OPEN METEO MARINE REFRESH]",{code:(error as any)?.code||"UNKNOWN",message:error instanceof Error?error.message:"unknown"});return json({ok:false,code:(error as any)?.code||"REFRESH_FAILED"},502)}finally{if(locked)await db.rpc("release_open_meteo_marine_lease",{p_owner:owner})}
});
