create table if not exists public.point_marine_source_mapping (
  point_id bigint primary key references public.points(id) on delete cascade,
  kma_grid text,
  khoa_wave_grid text,
  khoa_current_station text,
  khoa_tide_station text,
  warning_area_code text,
  mapping_source text not null default 'unmapped' check (mapping_source in ('automatic','partial','override','unmapped')),
  mapping_notes text,
  updated_at timestamptz not null default now()
);

create table if not exists public.khoa_wave_forecast_cache (
  id bigint generated by default as identity primary key,
  source text not null default 'KHOA_PRDN_WV3', grid_key text not null,
  issued_at timestamptz not null, forecast_at timestamptz not null,
  payload jsonb not null, normalized_data jsonb not null,
  fetched_at timestamptz not null, updated_at timestamptz not null default now(),
  status text not null default 'fresh' check (status in ('fresh','stale','failed')),
  stale boolean not null default false, response_bytes integer not null default 0,
  item_count integer not null default 0,
  unique (source, grid_key, issued_at, forecast_at)
);

create table if not exists public.khoa_current_forecast_cache (
  id bigint generated by default as identity primary key,
  source text not null default 'KHOA_CURRENT_FORECAST', station_code text not null,
  issued_at timestamptz not null, forecast_at timestamptz not null,
  payload jsonb not null, normalized_data jsonb not null,
  fetched_at timestamptz not null, updated_at timestamptz not null default now(),
  status text not null default 'fresh' check (status in ('fresh','stale','failed')),
  stale boolean not null default false, response_bytes integer not null default 0,
  item_count integer not null default 0,
  unique (source, station_code, issued_at, forecast_at)
);

create table if not exists public.khoa_tide_forecast_cache (
  id bigint generated by default as identity primary key,
  source text not null default 'KHOA_TIDE_FORECAST', station_code text not null,
  issued_at timestamptz not null, forecast_at timestamptz not null,
  payload jsonb not null, normalized_data jsonb not null,
  fetched_at timestamptz not null, updated_at timestamptz not null default now(),
  status text not null default 'fresh' check (status in ('fresh','stale','failed')),
  stale boolean not null default false, response_bytes integer not null default 0,
  item_count integer not null default 0,
  unique (source, station_code, issued_at, forecast_at)
);

create table if not exists public.khoa_marine_observation_cache (
  id bigint generated by default as identity primary key,
  source text not null, station_code text not null, observed_at timestamptz not null,
  payload jsonb not null, normalized_data jsonb not null,
  fetched_at timestamptz not null, updated_at timestamptz not null default now(),
  status text not null default 'fresh' check (status in ('fresh','stale','failed')),
  stale boolean not null default false, response_bytes integer not null default 0,
  item_count integer not null default 0,
  unique (source, station_code, observed_at)
);

create table if not exists public.kma_mid_sea_forecast_cache (
  id bigint generated by default as identity primary key,
  source text not null default 'KMA_MID_SEA', region_code text not null,
  issued_at timestamptz not null, forecast_at timestamptz not null,
  payload jsonb not null, normalized_data jsonb not null,
  fetched_at timestamptz not null, updated_at timestamptz not null default now(),
  status text not null default 'fresh' check (status in ('fresh','stale','failed')),
  stale boolean not null default false, response_bytes integer not null default 0,
  item_count integer not null default 0,
  unique (source, region_code, issued_at, forecast_at)
);

create index if not exists khoa_wave_latest_idx on public.khoa_wave_forecast_cache(grid_key, forecast_at desc) where status='fresh';
create index if not exists khoa_current_latest_idx on public.khoa_current_forecast_cache(station_code, forecast_at desc) where status='fresh';
create index if not exists khoa_tide_latest_idx on public.khoa_tide_forecast_cache(station_code, forecast_at desc) where status='fresh';
create index if not exists khoa_observation_latest_idx on public.khoa_marine_observation_cache(station_code, observed_at desc) where status='fresh';
create index if not exists kma_mid_sea_latest_idx on public.kma_mid_sea_forecast_cache(region_code, forecast_at desc) where status='fresh';

do $$
declare table_name text;
begin
  foreach table_name in array array['point_marine_source_mapping','khoa_wave_forecast_cache','khoa_current_forecast_cache','khoa_tide_forecast_cache','khoa_marine_observation_cache','kma_mid_sea_forecast_cache'] loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('revoke all on public.%I from anon, authenticated', table_name);
    execute format('grant select, insert, update, delete on public.%I to service_role', table_name);
  end loop;
end $$;

grant usage, select on sequence public.khoa_wave_forecast_cache_id_seq to service_role;
grant usage, select on sequence public.khoa_current_forecast_cache_id_seq to service_role;
grant usage, select on sequence public.khoa_tide_forecast_cache_id_seq to service_role;
grant usage, select on sequence public.khoa_marine_observation_cache_id_seq to service_role;
grant usage, select on sequence public.kma_mid_sea_forecast_cache_id_seq to service_role;

create or replace function public.cleanup_marine_forecast_cache()
returns bigint language plpgsql security definer set search_path=public as $$
declare deleted_count bigint := 0; affected bigint;
begin
  with protected as (select distinct on (grid_key) id from khoa_wave_forecast_cache where status='fresh' order by grid_key, issued_at desc, forecast_at desc), d as (delete from khoa_wave_forecast_cache c where c.fetched_at < now()-interval '7 days' and not exists(select 1 from protected p where p.id=c.id) returning 1) select count(*) into affected from d; deleted_count:=deleted_count+affected;
  with protected as (select distinct on (station_code) id from khoa_current_forecast_cache where status='fresh' order by station_code, issued_at desc, forecast_at desc), d as (delete from khoa_current_forecast_cache c where c.fetched_at < now()-interval '7 days' and not exists(select 1 from protected p where p.id=c.id) returning 1) select count(*) into affected from d; deleted_count:=deleted_count+affected;
  with protected as (select distinct on (station_code) id from khoa_tide_forecast_cache where status='fresh' order by station_code, issued_at desc, forecast_at desc), d as (delete from khoa_tide_forecast_cache c where c.fetched_at < now()-interval '7 days' and not exists(select 1 from protected p where p.id=c.id) returning 1) select count(*) into affected from d; deleted_count:=deleted_count+affected;
  with protected as (select distinct on (source,station_code) id from khoa_marine_observation_cache where status='fresh' order by source,station_code,observed_at desc), d as (delete from khoa_marine_observation_cache c where c.fetched_at < now()-interval '30 days' and not exists(select 1 from protected p where p.id=c.id) returning 1) select count(*) into affected from d; deleted_count:=deleted_count+affected;
  with protected as (select distinct on (region_code) id from kma_mid_sea_forecast_cache where status='fresh' order by region_code,issued_at desc,forecast_at desc), d as (delete from kma_mid_sea_forecast_cache c where c.fetched_at < now()-interval '7 days' and not exists(select 1 from protected p where p.id=c.id) returning 1) select count(*) into affected from d; deleted_count:=deleted_count+affected;
  return deleted_count;
end $$;
revoke all on function public.cleanup_marine_forecast_cache() from public, anon, authenticated;
grant execute on function public.cleanup_marine_forecast_cache() to service_role;
notify pgrst, 'reload schema';
