-- SNORKY 프렌즈 테이블 생성
create table if not exists public.snorky_friends (
  id bigint generated by default as identity primary key,
  user_id text not null,
  friend_user_id text not null,
  created_at timestamptz not null default timezone('utc'::text, now()),
  constraint chk_snorky_friends_no_self check (user_id <> friend_user_id)
);

-- 두 사용자 간 중복 관계 원천 방지 (A, B 순서 무관 1개 row만 허용)
create unique index if not exists uq_snorky_friends_pair
  on public.snorky_friends (least(user_id, friend_user_id), greatest(user_id, friend_user_id));

create index if not exists idx_snorky_friends_user
  on public.snorky_friends (user_id);

create index if not exists idx_snorky_friends_friend
  on public.snorky_friends (friend_user_id);

-- RLS 활성화
alter table public.snorky_friends enable row level security;

-- 권한 부여
grant select, insert, delete on public.snorky_friends to anon, authenticated, service_role;

-- RLS 정책 설정
do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'snorky_friends' and policyname = 'Allow select snorky_friends'
  ) then
    create policy "Allow select snorky_friends" on public.snorky_friends for select using (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'snorky_friends' and policyname = 'Allow insert snorky_friends'
  ) then
    create policy "Allow insert snorky_friends" on public.snorky_friends for insert with check (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'snorky_friends' and policyname = 'Allow delete snorky_friends'
  ) then
    create policy "Allow delete snorky_friends" on public.snorky_friends for delete using (true);
  end if;
end $$;
