-- 관리자 자격 인증/신고 관리 및 계정 제재

alter table public.user_profiles
  add column if not exists certification_status text,
  add column if not exists certification_organization text,
  add column if not exists certification_number text,
  add column if not exists suspended_until timestamptz,
  add column if not exists banned boolean not null default false;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.user_profiles'::regclass
      and conname = 'user_profiles_certification_status_check'
  ) then
    alter table public.user_profiles
      add constraint user_profiles_certification_status_check
      check (certification_status is null or certification_status in ('PENDING', 'APPROVED', 'REJECTED'));
  end if;
end $$;

create table if not exists public.certification_requests (
  id bigint generated by default as identity primary key,
  user_id text not null,
  nickname text,
  agency text not null,
  level text not null,
  certification_number text not null,
  status text not null default 'PENDING'
    check (status in ('PENDING', 'APPROVED', 'REJECTED')),
  rejection_reason text,
  requested_at timestamptz not null default timezone('utc'::text, now()),
  reviewed_at timestamptz,
  reviewed_by uuid
);

create index if not exists idx_certification_requests_status_requested
  on public.certification_requests (status, requested_at desc);
create index if not exists idx_certification_requests_user
  on public.certification_requests (user_id, requested_at desc);

create table if not exists public.user_reports (
  id bigint generated by default as identity primary key,
  target_user_id text not null,
  target_nickname text,
  reporter_user_id text,
  reporter_nickname text,
  reason text not null,
  details text,
  buddy_post_id bigint references public.buddy_posts(id) on delete set null,
  status text not null default 'PENDING'
    check (status in ('PENDING', 'REVIEWED', 'ACTIONED', 'DISMISSED')),
  action_type text
    check (action_type is null or action_type in ('WARNING', 'SUSPEND_3_DAYS', 'SUSPEND_7_DAYS', 'SUSPEND_30_DAYS', 'PERMANENT_BAN')),
  action_reason text,
  reported_at timestamptz not null default timezone('utc'::text, now()),
  reviewed_at timestamptz,
  reviewed_by uuid
);

create index if not exists idx_user_reports_status_reported
  on public.user_reports (status, reported_at desc);
create index if not exists idx_user_reports_target
  on public.user_reports (target_user_id, reported_at desc);

create table if not exists public.user_moderation_actions (
  id bigint generated by default as identity primary key,
  user_id text not null,
  report_id bigint references public.user_reports(id) on delete set null,
  action_type text not null
    check (action_type in ('WARNING', 'SUSPEND_3_DAYS', 'SUSPEND_7_DAYS', 'SUSPEND_30_DAYS', 'PERMANENT_BAN')),
  reason text,
  suspended_until timestamptz,
  created_at timestamptz not null default timezone('utc'::text, now()),
  created_by uuid not null
);

create index if not exists idx_user_moderation_actions_user
  on public.user_moderation_actions (user_id, created_at desc);

create or replace function public.is_snorky_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_users where user_id = auth.uid()
  );
$$;

revoke all on function public.is_snorky_admin() from public;
grant execute on function public.is_snorky_admin() to authenticated, service_role;

alter table public.certification_requests enable row level security;
alter table public.user_reports enable row level security;
alter table public.user_moderation_actions enable row level security;

revoke all on public.certification_requests from anon, authenticated;
revoke all on public.user_reports from anon, authenticated;
revoke all on public.user_moderation_actions from anon, authenticated;
grant select, update on public.certification_requests to authenticated;
grant select, update on public.user_reports to authenticated;
grant select on public.user_moderation_actions to authenticated;
grant all on public.certification_requests, public.user_reports, public.user_moderation_actions to service_role;
grant usage, select on sequence public.certification_requests_id_seq, public.user_reports_id_seq, public.user_moderation_actions_id_seq to service_role;

create policy "Admins manage certification requests"
  on public.certification_requests
  for all to authenticated
  using (public.is_snorky_admin())
  with check (public.is_snorky_admin());

create policy "Admins manage user reports"
  on public.user_reports
  for all to authenticated
  using (public.is_snorky_admin())
  with check (public.is_snorky_admin());

create policy "Admins read moderation actions"
  on public.user_moderation_actions
  for select to authenticated
  using (public.is_snorky_admin());

create or replace function public.submit_user_report(
  p_target_user_id text,
  p_target_nickname text,
  p_reporter_user_id text,
  p_reporter_nickname text,
  p_reason text,
  p_details text,
  p_buddy_post_id bigint default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id bigint;
  v_reporter_banned boolean;
begin
  if nullif(btrim(p_target_user_id), '') is null or nullif(btrim(p_reason), '') is null then
    raise exception 'INVALID_REPORT';
  end if;

  if nullif(btrim(p_reporter_user_id), '') is not null then
    select banned into v_reporter_banned
    from public.user_profiles
    where provider_user_id = btrim(p_reporter_user_id)
    order by (provider = 'kakao') desc, id desc
    limit 1;
    if coalesce(v_reporter_banned, false) then raise exception 'ACCOUNT_BANNED'; end if;
  end if;

  insert into public.user_reports (
    target_user_id, target_nickname, reporter_user_id, reporter_nickname,
    reason, details, buddy_post_id, status
  ) values (
    btrim(p_target_user_id), nullif(btrim(p_target_nickname), ''),
    nullif(btrim(p_reporter_user_id), ''), nullif(btrim(p_reporter_nickname), ''),
    btrim(p_reason), nullif(btrim(p_details), ''), p_buddy_post_id, 'PENDING'
  ) returning id into v_id;

  return v_id;
end;
$$;

revoke all on function public.submit_user_report(text, text, text, text, text, text, bigint) from public;
grant execute on function public.submit_user_report(text, text, text, text, text, text, bigint) to anon, authenticated, service_role;

create or replace function public.review_certification_request(
  p_request_id bigint,
  p_status text,
  p_rejection_reason text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_request public.certification_requests%rowtype;
  v_now timestamptz := timezone('utc'::text, now());
begin
  if not public.is_snorky_admin() then
    raise exception 'ADMIN_REQUIRED';
  end if;
  if p_status not in ('APPROVED', 'REJECTED') then
    raise exception 'INVALID_CERTIFICATION_STATUS';
  end if;
  if p_status = 'REJECTED' and nullif(btrim(p_rejection_reason), '') is null then
    raise exception 'REJECTION_REASON_REQUIRED';
  end if;

  select * into v_request
  from public.certification_requests
  where id = p_request_id
  for update;

  if not found then raise exception 'CERTIFICATION_REQUEST_NOT_FOUND'; end if;
  if v_request.status <> 'PENDING' then raise exception 'CERTIFICATION_REQUEST_ALREADY_REVIEWED'; end if;

  update public.certification_requests
  set status = p_status,
      rejection_reason = case when p_status = 'REJECTED' then btrim(p_rejection_reason) else null end,
      reviewed_at = v_now,
      reviewed_by = auth.uid()
  where id = p_request_id;

  update public.user_profiles
  set aida_level = case when p_status = 'APPROVED' then v_request.level else aida_level end,
      certification_status = p_status,
      certification_organization = case when p_status = 'APPROVED' then v_request.agency else certification_organization end,
      certification_number = case when p_status = 'APPROVED' then v_request.certification_number else certification_number end,
      updated_at = v_now
  where provider_user_id = v_request.user_id;
  if not found then raise exception 'CERTIFICATION_PROFILE_NOT_FOUND'; end if;

  return jsonb_build_object('id', p_request_id, 'status', p_status, 'reviewed_at', v_now, 'reviewed_by', auth.uid());
end;
$$;

revoke all on function public.review_certification_request(bigint, text, text) from public;
grant execute on function public.review_certification_request(bigint, text, text) to authenticated, service_role;

create or replace function public.moderate_user_report(
  p_report_id bigint,
  p_status text,
  p_action_type text default null,
  p_action_reason text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_report public.user_reports%rowtype;
  v_now timestamptz := timezone('utc'::text, now());
  v_suspended_until timestamptz;
begin
  if not public.is_snorky_admin() then raise exception 'ADMIN_REQUIRED'; end if;
  if p_status not in ('PENDING', 'REVIEWED', 'ACTIONED', 'DISMISSED') then raise exception 'INVALID_REPORT_STATUS'; end if;
  if p_action_type is not null and p_action_type not in ('WARNING', 'SUSPEND_3_DAYS', 'SUSPEND_7_DAYS', 'SUSPEND_30_DAYS', 'PERMANENT_BAN') then
    raise exception 'INVALID_ACTION_TYPE';
  end if;

  select * into v_report from public.user_reports where id = p_report_id for update;
  if not found then raise exception 'REPORT_NOT_FOUND'; end if;

  if p_action_type is not null then
    p_status := 'ACTIONED';
    v_suspended_until := case p_action_type
      when 'SUSPEND_3_DAYS' then v_now + interval '3 days'
      when 'SUSPEND_7_DAYS' then v_now + interval '7 days'
      when 'SUSPEND_30_DAYS' then v_now + interval '30 days'
      else null
    end;

    if p_action_type = 'PERMANENT_BAN' then
      update public.user_profiles
      set banned = true, suspended_until = null, updated_at = v_now
      where provider_user_id = v_report.target_user_id;
      if not found then raise exception 'MODERATION_PROFILE_NOT_FOUND'; end if;
    elsif v_suspended_until is not null then
      update public.user_profiles
      set suspended_until = greatest(coalesce(suspended_until, v_suspended_until), v_suspended_until), updated_at = v_now
      where provider_user_id = v_report.target_user_id;
      if not found then raise exception 'MODERATION_PROFILE_NOT_FOUND'; end if;
    end if;

    insert into public.user_moderation_actions (
      user_id, report_id, action_type, reason, suspended_until, created_by
    ) values (
      v_report.target_user_id, p_report_id, p_action_type,
      nullif(btrim(p_action_reason), ''), v_suspended_until, auth.uid()
    );
  end if;

  update public.user_reports
  set status = p_status,
      action_type = coalesce(p_action_type, action_type),
      action_reason = case when p_action_type is not null then nullif(btrim(p_action_reason), '') else action_reason end,
      reviewed_at = v_now,
      reviewed_by = auth.uid()
  where id = p_report_id;

  return jsonb_build_object(
    'id', p_report_id, 'status', p_status, 'action_type', p_action_type,
    'suspended_until', v_suspended_until, 'reviewed_at', v_now, 'reviewed_by', auth.uid()
  );
end;
$$;

revoke all on function public.moderate_user_report(bigint, text, text, text) from public;
grant execute on function public.moderate_user_report(bigint, text, text, text) to authenticated, service_role;

create or replace function public.protect_user_moderation_fields()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if coalesce(auth.role(), '') = 'service_role' or public.is_snorky_admin() then return new; end if;
  if coalesce(old.banned, false) then raise exception 'ACCOUNT_BANNED'; end if;
  if new.certification_status is distinct from old.certification_status
    or new.certification_organization is distinct from old.certification_organization
    or new.certification_number is distinct from old.certification_number
    or new.suspended_until is distinct from old.suspended_until
    or new.banned is distinct from old.banned then
    raise exception 'PROTECTED_PROFILE_FIELDS';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_protect_user_moderation_fields on public.user_profiles;
create trigger trg_protect_user_moderation_fields
before update on public.user_profiles
for each row execute function public.protect_user_moderation_fields();

create or replace function public.enforce_user_posting_access()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id text;
  v_banned boolean;
  v_suspended_until timestamptz;
begin
  if coalesce(auth.role(), '') = 'service_role' or public.is_snorky_admin() then return new; end if;
  v_user_id := case tg_table_name
    when 'buddy_posts' then to_jsonb(new) ->> 'user_id'
    when 'buddy_applications' then to_jsonb(new) ->> 'applicant_user_id'
    when 'snorky_friends' then to_jsonb(new) ->> 'user_id'
    else null
  end;

  select banned, suspended_until into v_banned, v_suspended_until
  from public.user_profiles
  where provider_user_id = v_user_id
  order by (provider = 'kakao') desc, id desc
  limit 1;

  if coalesce(v_banned, false) then raise exception 'ACCOUNT_BANNED'; end if;
  if v_suspended_until is not null and v_suspended_until > timezone('utc'::text, now()) then
    raise exception 'ACCOUNT_SUSPENDED_UNTIL:%', v_suspended_until;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_buddy_posts_user_access on public.buddy_posts;
create trigger trg_buddy_posts_user_access before insert on public.buddy_posts
for each row execute function public.enforce_user_posting_access();

drop trigger if exists trg_buddy_applications_user_access on public.buddy_applications;
create trigger trg_buddy_applications_user_access before insert on public.buddy_applications
for each row execute function public.enforce_user_posting_access();

drop trigger if exists trg_snorky_friends_user_access on public.snorky_friends;
create trigger trg_snorky_friends_user_access before insert on public.snorky_friends
for each row execute function public.enforce_user_posting_access();

notify pgrst, 'reload schema';
