-- 실내다이빙 센터 45개 대표 이미지(hero_image_url, hero_image_source) 스티치 배너 자산 재배열 마이그레이션

alter table public.indoor_diving_centers
  add column if not exists hero_image_url text,
  add column if not exists hero_image_source text;

update public.indoor_diving_centers set
  hero_image_url = case name
    when '송파 올림픽수영장 다이빙풀' then 'https://www.ksponco.or.kr/img/common/og_image.png'
    when 'KUA 잠실다이빙풀장' then 'https://kua.or.kr/opengraph-image.jpg'
    when '딥스테이션' then 'https://images.unsplash.com/photo-1518837695005-2083093ee35b?w=800&auto=format&fit=crop&q=80'
    when '파라다이브35' then 'https://paradive.co.kr/service/pc/assets/img/main_section01_object01.svg'
    when '송도 스포츠파크 잠수풀' then 'https://www.eco-i.or.kr/images/blog.png'
    when 'K26 잠수풀' then 'https://lh3.googleusercontent.com/aida/AEtjO1XWDU0WR2IxrLtyZgRAsae12NDDQ3w4cPmQPw5PYVSFXFBtKZgk92nDroUc0FidPlwWHQ9L7i4yNzXdfT7URiNz4bxn79SWCy-liaCbA8rzbg_z_sMaqMo6bToiq4M5l-VPQ54G403fiV8Gu3RCRPjwx7QuussYSo0Xe7xEtKvGIYGuVczmZ3tW9fckqzafo4auRuYn6dy5HOWx1zpEGVx8Jb7_NamWA7NC0_W1cE2GEtURflmvga7l6w'
    when '테마 오산 잠수풀' then 'https://lh3.googleusercontent.com/aida/AEtjO1Xkt7JS4V5RWghv4kExAdhHj_etOyzXu5ea8E-oy7Ht2tWL_i6W93vMr49ovzGg2Op8GnXSpRPitrwMVdCTw2Ald8LWxz_tSBnm17Ix6B_uWFyATWUuuyST_wMu9Dt5nHAMIBv2F8Rnd-3siMAeFOfCjDeveh6AxD4voBFf8beqx4HcjBDjeF2FmYHMcVKOseNioO_BDXZmXryDSRTQooUDFZaKlDc5QNO2USt1fXKWp8iyeOxAJ1_S0g'
    when '씨네블루 파주 잠수풀' then 'https://lh3.googleusercontent.com/aida/AEtjO1WLR_C_n4amRuhLBRMqEg02xgEI4obRFs_3jvc--SoaJb3I57PxTS9nWGfQuT0yOFiIyyXbwgQwgvCCTItAYMOQDIc6rkYzEcDWmILAmevc1MyvtbBMxF696TPNpykJaztzeOZjvtv8F8_MpW8pM5vo1MCaiYbu2zJzs24TDdCPBFfk9wnTqyi2042HDn83sAirIm4pLtTdq5cVKbx2vxhMLmjqmflG9jP-fiFjY3MRQ8z7f42h8UZa2g'
    when '뉴서울다이빙풀' then 'https://lh3.googleusercontent.com/aida/AEtjO1WMjhjP_JSBJGnP2vrCVE0eA-fBjVWKrZEHlpOKuz7CKgFKc4H9cW3TIDicWoUqiE3nMhg-VBSc_82gsoYGxuhqOczhJaeDJ1yUg0fxiqQb3oe3UU2dcJXXu5nYlIIbV1g6s5v4CEmJmWIduuWtLQNN9gZxEJI2tK4fvRD9Adtw3m6PSwtJlWDo_cR5o4g-zzsItPYhZKvWAte5RSCc7nEX3rc7GyDowjexk9yVhSd_R2hrHqSWmJEIMA'
    when '대부잠수풀' then 'https://lh3.googleusercontent.com/aida/AEtjO1VWVlZjClhEcHnejMr_1RhsEPNy59RdnVKHUZJ5MVSscYjTYG76EQRl6CP_OPLxObGCkOBoWeXhGybHYsyKpcsnd7NL_Pzixxehn86-iPIXngsMUAsASi-pn_4bs3drPQLmfcuWoqiiyPHARz1HhppQKl2kfo2nn9KQQHVgvMtY_QBzKSs2xT2QkRBVC2KcVI5OlDYoCkSNfcLn5YwsnNQVEq2JeI4KQ0UccDMPX-AiYpXczio2b2Dt5fg'
    when '서브마린다이빙풀' then 'https://lh3.googleusercontent.com/aida/AEtjO1WNPdy3mzjGo-8EuuME9V2a2R9NxP6PPEywM2UVhMK40ZonWUHlX_d1jue4JYsIDyr0F667Y695YLxfR4WlQD1n_5D_BE9ZdmN8qrqHHcgSFEipU0dXim-ytTDwQDvMsWj0dcwlD1pAJ_lE_CujcHJ_WfCuPlfaQoFbJUiR1IlkrTPKN34dpfLYfe44u6V61hHOF8f-RFzNh0tElN_ZrRRMv6FxVbkaG3QmRUDGwjWn5ZmsOKVICsg6VlU'
    when '수원 스킨스쿠버 다이빙풀' then 'https://lh3.googleusercontent.com/aida/AEtjO1Xw6zdU45ZPxCg7-LKi08TVqfQgLrF71ZzjXnNlrnWPWn4xXaQ5e9EHzA6xwop_MGcj7xSrjliPUhVmuivFEW4V7RFbJytpCUTKZW3OAPruG3E2y60yBSzLu553mrwDWNk6-9wLmT5KQw80Vb3CKxLTqQ8oHbrflw8pLSVcuNAtSIPRN1kdwhjf3kBD9ptXMGOWnu7zJI_kt_82oE16k5lJr4-SSETHNMQ0O50iTVndCWxSBBpp-I-lRg'
    when '메르다이빙센터 일산점' then 'https://lh3.googleusercontent.com/aida/AEtjO1Vkd2VAefAcdmMguWryhvVFM-UFWU5ojp_5R3fLyxEaCRnuarLqppKUTG8PQQ2NflvHaUXlxS0bwwh_ctbD0sUXHc4_kMVcqabR0PTluO_BZExiG1Yz5QCAnjpF7d0UHY8-m0i_IzL4aA-482XAzQ5qi79iTw1R_DYKjzr-Q_BIGWQfZVMEBbCvWv77soKVUQEadedVRjy-1a1XXCAzRMrI-SPsFxHzLk1Of2E0W5lf20GzCVkoSf8m-64'
    when '아르피아 잠수풀' then 'https://www.yuc.or.kr/bbsDown/main_banner/2026030768981992328.jpg'
    when '포프라자' then 'https://lh3.googleusercontent.com/aida/AEtjO1WOGIv4BfDVYDRtksLiI47ASh5QjPLT4ZH0rJB5R0qjnaYDpB7YMNAKUAEWzVEJMY1HJNR8-sgmt4VbHWieHBXsM6qY9q29BQDxtd-jmZ_8iCRxm2L8VhWl--kgRsvHap5ojEZ_SQesNP9nXYVz2eLS9GivobDjNg6CpBID1V9Jszb6KG74Y2lh9ZO63XN914nkUbfKUwBKoDyMoatlovIl5nfAwRSd5HnahttIM_Oi8m4U0wcz396zV5s'
    when '양주에코스포츠센터' then 'https://lh3.googleusercontent.com/aida/AEtjO1XpjwvlyQFVyKZaYhLwrs7cD_kx9YJgBCIkRepERw-Q_5iVQDOvgrRnEHMJ7CUQFjsJmyiXWQDl9l00d1FuMzTE4FjokBjfjC4yJ2WRb6Cd5UrlhgPO5ODkbSh2IZYPSKXiF5ohwKV7RLHujEyJTEr4R0jve7Vny90GvgWBfghPSuR0LLy4ydGJC-JJnXLc9TdC4TWvRTltOeBfOtvevywWE0uTly0hQaop9RR0GKX5iZ8LPmMyifl2LkY'
    when '수작코리아 수중촬영장' then 'https://lh3.googleusercontent.com/aida/AEtjO1XWDU0WR2IxrLtyZgRAsae12NDDQ3w4cPmQPw5PYVSFXFBtKZgk92nDroUc0FidPlwWHQ9L7i4yNzXdfT7URiNz4bxn79SWCy-liaCbA8rzbg_z_sMaqMo6bToiq4M5l-VPQ54G403fiV8Gu3RCRPjwx7QuussYSo0Xe7xEtKvGIYGuVczmZ3tW9fckqzafo4auRuYn6dy5HOWx1zpEGVx8Jb7_NamWA7NC0_W1cE2GEtURflmvga7l6w'
    when '용문국민체육센터' then 'https://lh3.googleusercontent.com/aida/AEtjO1Xkt7JS4V5RWghv4kExAdhHj_etOyzXu5ea8E-oy7Ht2tWL_i6W93vMr49ovzGg2Op8GnXSpRPitrwMVdCTw2Ald8LWxz_tSBnm17Ix6B_uWFyATWUuuyST_wMu9Dt5nHAMIBv2F8Rnd-3siMAeFOfCjDeveh6AxD4voBFf8beqx4HcjBDjeF2FmYHMcVKOseNioO_BDXZmXryDSRTQooUDFZaKlDc5QNO2USt1fXKWp8iyeOxAJ1_S0g'
    when '아쿠아라인 다목적풀' then 'https://lh3.googleusercontent.com/aida/AEtjO1WLR_C_n4amRuhLBRMqEg02xgEI4obRFs_3jvc--SoaJb3I57PxTS9nWGfQuT0yOFiIyyXbwgQwgvCCTItAYMOQDIc6rkYzEcDWmILAmevc1MyvtbBMxF696TPNpykJaztzeOZjvtv8F8_MpW8pM5vo1MCaiYbu2zJzs24TDdCPBFfk9wnTqyi2042HDn83sAirIm4pLtTdq5cVKbx2vxhMLmjqmflG9jP-fiFjY3MRQ8z7f42h8UZa2g'
    when '웨이브파크 블루홀라군' then 'https://www.wavepark.co.kr/assets/wavepark/img/n-lesson-01.jpg'
    when '화성그린환경센터' then 'https://lh3.googleusercontent.com/aida/AEtjO1WMjhjP_JSBJGnP2vrCVE0eA-fBjVWKrZEHlpOKuz7CKgFKc4H9cW3TIDicWoUqiE3nMhg-VBSc_82gsoYGxuhqOczhJaeDJ1yUg0fxiqQb3oe3UU2dcJXXu5nYlIIbV1g6s5v4CEmJmWIduuWtLQNN9gZxEJI2tK4fvRD9Adtw3m6PSwtJlWDo_cR5o4g-zzsItPYhZKvWAte5RSCc7nEX3rc7GyDowjexk9yVhSd_R2hrHqSWmJEIMA'
    when '알프스다이빙' then 'https://lh3.googleusercontent.com/aida/AEtjO1VWVlZjClhEcHnejMr_1RhsEPNy59RdnVKHUZJ5MVSscYjTYG76EQRl6CP_OPLxObGCkOBoWeXhGybHYsyKpcsnd7NL_Pzixxehn86-iPIXngsMUAsASi-pn_4bs3drPQLmfcuWoqiiyPHARz1HhppQKl2kfo2nn9KQQHVgvMtY_QBzKSs2xT2QkRBVC2KcVI5OlDYoCkSNfcLn5YwsnNQVEq2JeI4KQ0UccDMPX-AiYpXczio2b2Dt5fg'
    when '충북학생수영장' then 'https://www.cbe.go.kr/images/template/TA01/layout/img_coming.png'
    when '강릉 북부수영장' then 'https://lh3.googleusercontent.com/aida/AEtjO1WNPdy3mzjGo-8EuuME9V2a2R9NxP6PPEywM2UVhMK40ZonWUHlX_d1jue4JYsIDyr0F667Y695YLxfR4WlQD1n_5D_BE9ZdmN8qrqHHcgSFEipU0dXim-ytTDwQDvMsWj0dcwlD1pAJ_lE_CujcHJ_WfCuPlfaQoFbJUiR1IlkrTPKN34dpfLYfe44u6V61hHOF8f-RFzNh0tElN_ZrRRMv6FxVbkaG3QmRUDGwjWn5ZmsOKVICsg6VlU'
    when '강릉국민체육센터' then 'https://lh3.googleusercontent.com/aida/AEtjO1Xw6zdU45ZPxCg7-LKi08TVqfQgLrF71ZzjXnNlrnWPWn4xXaQ5e9EHzA6xwop_MGcj7xSrjliPUhVmuivFEW4V7RFbJytpCUTKZW3OAPruG3E2y60yBSzLu553mrwDWNk6-9wLmT5KQw80Vb3CKxLTqQ8oHbrflw8pLSVcuNAtSIPRN1kdwhjf3kBD9ptXMGOWnu7zJI_kt_82oE16k5lJr4-SSETHNMQ0O50iTVndCWxSBBpp-I-lRg'
    when '올덴K10잠수풀' then 'https://lh3.googleusercontent.com/aida/AEtjO1Vkd2VAefAcdmMguWryhvVFM-UFWU5ojp_5R3fLyxEaCRnuarLqppKUTG8PQQ2NflvHaUXlxS0bwwh_ctbD0sUXHc4_kMVcqabR0PTluO_BZExiG1Yz5QCAnjpF7d0UHY8-m0i_IzL4aA-482XAzQ5qi79iTw1R_DYKjzr-Q_BIGWQfZVMEBbCvWv77soKVUQEadedVRjy-1a1XXCAzRMrI-SPsFxHzLk1Of2E0W5lf20GzCVkoSf8m-64'
    when '패스나인 다이빙센터' then 'https://lh3.googleusercontent.com/aida/AEtjO1WOGIv4BfDVYDRtksLiI47ASh5QjPLT4ZH0rJB5R0qjnaYDpB7YMNAKUAEWzVEJMY1HJNR8-sgmt4VbHWieHBXsM6qY9q29BQDxtd-jmZ_8iCRxm2L8VhWl--kgRsvHap5ojEZ_SQesNP9nXYVz2eLS9GivobDjNg6CpBID1V9Jszb6KG74Y2lh9ZO63XN914nkUbfKUwBKoDyMoatlovIl5nfAwRSd5HnahttIM_Oi8m4U0wcz396zV5s'
    when '울진해양레포츠센터' then 'https://lh3.googleusercontent.com/aida/AEtjO1XpjwvlyQFVyKZaYhLwrs7cD_kx9YJgBCIkRepERw-Q_5iVQDOvgrRnEHMJ7CUQFjsJmyiXWQDl9l00d1FuMzTE4FjokBjfjC4yJ2WRb6Cd5UrlhgPO5ODkbSh2IZYPSKXiF5ohwKV7RLHujEyJTEr4R0jve7Vny90GvgWBfghPSuR0LLy4ydGJC-JJnXLc9TdC4TWvRTltOeBfOtvevywWE0uTly0hQaop9RR0GKX5iZ8LPmMyifl2LkY'
    when '북항마리나 다이빙풀' then 'https://lh3.googleusercontent.com/aida/AEtjO1XWDU0WR2IxrLtyZgRAsae12NDDQ3w4cPmQPw5PYVSFXFBtKZgk92nDroUc0FidPlwWHQ9L7i4yNzXdfT7URiNz4bxn79SWCy-liaCbA8rzbg_z_sMaqMo6bToiq4M5l-VPQ54G403fiV8Gu3RCRPjwx7QuussYSo0Xe7xEtKvGIYGuVczmZ3tW9fckqzafo4auRuYn6dy5HOWx1zpEGVx8Jb7_NamWA7NC0_W1cE2GEtURflmvga7l6w'
    when '밀양 아리랑 잠수풀' then 'https://www.myfmc.or.kr/img/intro_img/cont01.jpg'
    when '문수실내수영장 다이빙풀' then 'https://www.uuc.or.kr/template/resources/images/basic/title.png'
    when '사직실내수영장 다이빙풀' then 'https://www.bisco.or.kr/image/2025/main/main-visual-copy.png'
    when '고성해양레포츠아카데미' then 'https://www.goseong.go.kr/images/Potal/layout/errorImg.png'
    when '송도해양레포츠센터 잠수풀' then 'https://www.bsseogu.go.kr/img/tour/Main/2024mvisual-img10.png'
    when '풀식스다이빙풀' then 'https://lh3.googleusercontent.com/aida/AEtjO1Xkt7JS4V5RWghv4kExAdhHj_etOyzXu5ea8E-oy7Ht2tWL_i6W93vMr49ovzGg2Op8GnXSpRPitrwMVdCTw2Ald8LWxz_tSBnm17Ix6B_uWFyATWUuuyST_wMu9Dt5nHAMIBv2F8Rnd-3siMAeFOfCjDeveh6AxD4voBFf8beqx4HcjBDjeF2FmYHMcVKOseNioO_BDXZmXryDSRTQooUDFZaKlDc5QNO2USt1fXKWp8iyeOxAJ1_S0g'
    when '창원실내수영장 다이빙풀' then 'https://www.cwsisul.or.kr/images/main_popup02_btn01.png'
    when 'DIT 잠수풀장' then 'https://www.dit.ac.kr/kr/_Img/Intro/2024/lcon01.png'
    when '염주체육관 다이빙풀' then 'https://lh3.googleusercontent.com/aida/AEtjO1WLR_C_n4amRuhLBRMqEg02xgEI4obRFs_3jvc--SoaJb3I57PxTS9nWGfQuT0yOFiIyyXbwgQwgvCCTItAYMOQDIc6rkYzEcDWmILAmevc1MyvtbBMxF696TPNpykJaztzeOZjvtv8F8_MpW8pM5vo1MCaiYbu2zJzs24TDdCPBFfk9wnTqyi2042HDn83sAirIm4pLtTdq5cVKbx2vxhMLmjqmflG9jP-fiFjY3MRQ8z7f42h8UZa2g'
    when '전북잠수전문학교 익산점' then 'https://lh3.googleusercontent.com/aida/AEtjO1WMjhjP_JSBJGnP2vrCVE0eA-fBjVWKrZEHlpOKuz7CKgFKc4H9cW3TIDicWoUqiE3nMhg-VBSc_82gsoYGxuhqOczhJaeDJ1yUg0fxiqQb3oe3UU2dcJXXu5nYlIIbV1g6s5v4CEmJmWIduuWtLQNN9gZxEJI2tK4fvRD9Adtw3m6PSwtJlWDo_cR5o4g-zzsItPYhZKvWAte5RSCc7nEX3rc7GyDowjexk9yVhSd_R2hrHqSWmJEIMA'
    when '여수시청소년해양교육원 잠수풀' then 'https://lh3.googleusercontent.com/aida/AEtjO1VWVlZjClhEcHnejMr_1RhsEPNy59RdnVKHUZJ5MVSscYjTYG76EQRl6CP_OPLxObGCkOBoWeXhGybHYsyKpcsnd7NL_Pzixxehn86-iPIXngsMUAsASi-pn_4bs3drPQLmfcuWoqiiyPHARz1HhppQKl2kfo2nn9KQQHVgvMtY_QBzKSs2xT2QkRBVC2KcVI5OlDYoCkSNfcLn5YwsnNQVEq2JeI4KQ0UccDMPX-AiYpXczio2b2Dt5fg'
    when '군산오션팔레트 잠수풀' then 'https://lh3.googleusercontent.com/aida/AEtjO1WNPdy3mzjGo-8EuuME9V2a2R9NxP6PPEywM2UVhMK40ZonWUHlX_d1jue4JYsIDyr0F667Y695YLxfR4WlQD1n_5D_BE9ZdmN8qrqHHcgSFEipU0dXim-ytTDwQDvMsWj0dcwlD1pAJ_lE_CujcHJ_WfCuPlfaQoFbJUiR1IlkrTPKN34dpfLYfe44u6V61hHOF8f-RFzNh0tElN_ZrRRMv6FxVbkaG3QmRUDGwjWn5ZmsOKVICsg6VlU'
    when '전주완산수영장 다이빙풀' then 'https://lh3.googleusercontent.com/aida/AEtjO1Xw6zdU45ZPxCg7-LKi08TVqfQgLrF71ZzjXnNlrnWPWn4xXaQ5e9EHzA6xwop_MGcj7xSrjliPUhVmuivFEW4V7RFbJytpCUTKZW3OAPruG3E2y60yBSzLu553mrwDWNk6-9wLmT5KQw80Vb3CKxLTqQ8oHbrflw8pLSVcuNAtSIPRN1kdwhjf3kBD9ptXMGOWnu7zJI_kt_82oE16k5lJr4-SSETHNMQ0O50iTVndCWxSBBpp-I-lRg'
    when '다이브자이언트 제주교육센터' then 'https://lh3.googleusercontent.com/aida/AEtjO1Vkd2VAefAcdmMguWryhvVFM-UFWU5ojp_5R3fLyxEaCRnuarLqppKUTG8PQQ2NflvHaUXlxS0bwwh_ctbD0sUXHc4_kMVcqabR0PTluO_BZExiG1Yz5QCAnjpF7d0UHY8-m0i_IzL4aA-482XAzQ5qi79iTw1R_DYKjzr-Q_BIGWQfZVMEBbCvWv77soKVUQEadedVRjy-1a1XXCAzRMrI-SPsFxHzLk1Of2E0W5lf20GzCVkoSf8m-64'
    when '수원 월드컵경기장 다이빙풀' then 'https://lh3.googleusercontent.com/aida/AEtjO1WOGIv4BfDVYDRtksLiI47ASh5QjPLT4ZH0rJB5R0qjnaYDpB7YMNAKUAEWzVEJMY1HJNR8-sgmt4VbHWieHBXsM6qY9q29BQDxtd-jmZ_8iCRxm2L8VhWl--kgRsvHap5ojEZ_SQesNP9nXYVz2eLS9GivobDjNg6CpBID1V9Jszb6KG74Y2lh9ZO63XN914nkUbfKUwBKoDyMoatlovIl5nfAwRSd5HnahttIM_Oi8m4U0wcz396zV5s'
    when '아산 실내스킨스쿠버 다이빙풀 (배미수영장)' then 'https://www.asanfmc.or.kr/new/upload_data/banner/jwpnmnqi.jpg'
    else image_url
  end,
  hero_image_source = case name
    when '송파 올림픽수영장 다이빙풀' then 'official'
    when 'KUA 잠실다이빙풀장' then 'official'
    when '딥스테이션' then 'fallback'
    when '파라다이브35' then 'official'
    when '송도 스포츠파크 잠수풀' then 'official'
    when 'K26 잠수풀' then 'fallback'
    when '테마 오산 잠수풀' then 'fallback'
    when '씨네블루 파주 잠수풀' then 'fallback'
    when '뉴서울다이빙풀' then 'fallback'
    when '대부잠수풀' then 'fallback'
    when '서브마린다이빙풀' then 'fallback'
    when '수원 스킨스쿠버 다이빙풀' then 'fallback'
    when '메르다이빙센터 일산점' then 'fallback'
    when '아르피아 잠수풀' then 'official'
    when '포프라자' then 'fallback'
    when '양주에코스포츠센터' then 'fallback'
    when '수작코리아 수중촬영장' then 'fallback'
    when '용문국민체육센터' then 'fallback'
    when '아쿠아라인 다목적풀' then 'fallback'
    when '웨이브파크 블루홀라군' then 'official'
    when '화성그린환경센터' then 'fallback'
    when '알프스다이빙' then 'fallback'
    when '충북학생수영장' then 'official'
    when '강릉 북부수영장' then 'fallback'
    when '강릉국민체육센터' then 'fallback'
    when '올덴K10잠수풀' then 'fallback'
    when '패스나인 다이빙센터' then 'fallback'
    when '울진해양레포츠센터' then 'fallback'
    when '북항마리나 다이빙풀' then 'fallback'
    when '밀양 아리랑 잠수풀' then 'official'
    when '문수실내수영장 다이빙풀' then 'official'
    when '사직실내수영장 다이빙풀' then 'official'
    when '고성해양레포츠아카데미' then 'official'
    when '송도해양레포츠센터 잠수풀' then 'official'
    when '풀식스다이빙풀' then 'fallback'
    when '창원실내수영장 다이빙풀' then 'official'
    when 'DIT 잠수풀장' then 'official'
    when '염주체육관 다이빙풀' then 'fallback'
    when '전북잠수전문학교 익산점' then 'fallback'
    when '여수시청소년해양교육원 잠수풀' then 'fallback'
    when '군산오션팔레트 잠수풀' then 'fallback'
    when '전주완산수영장 다이빙풀' then 'fallback'
    when '다이브자이언트 제주교육센터' then 'fallback'
    when '수원 월드컵경기장 다이빙풀' then 'fallback'
    when '아산 실내스킨스쿠버 다이빙풀 (배미수영장)' then 'official'
    else 'fallback'
  end;