-- 신고 상세에서 관리자만 버디 공고를 취소할 수 있도록 별도 액션과 감사 기록을 추가한다.

create table if not exists public.buddy_post_moderation_actions (
  id bigint generated by default as identity primary key,
  report_id bigint not null references public.user_reports(id) on delete restrict,
  buddy_post_id bigint not null references public.buddy_posts(id) on delete restrict,
  reason text,
  created_at timestamptz not null default timezone('utc'::text, now()),
  created_by uuid not null
);

create index if not exists idx_buddy_post_moderation_actions_post
  on public.buddy_post_moderation_actions (buddy_post_id, created_at desc);

alter table public.buddy_post_moderation_actions enable row level security;
revoke all on public.buddy_post_moderation_actions from anon, authenticated;
grant select on public.buddy_post_moderation_actions to authenticated;
grant all on public.buddy_post_moderation_actions to service_role;
grant usage, select on sequence public.buddy_post_moderation_actions_id_seq to service_role;

drop policy if exists "Admins read buddy post moderation actions" on public.buddy_post_moderation_actions;
create policy "Admins read buddy post moderation actions"
  on public.buddy_post_moderation_actions
  for select to authenticated
  using (public.is_snorky_admin());

create or replace function public.moderate_buddy_post_admin(
  p_report_id bigint,
  p_buddy_post_id bigint,
  p_reason text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_report public.user_reports%rowtype;
  v_post public.buddy_posts%rowtype;
  v_now timestamptz := timezone('utc'::text, now());
  v_cancelled_applications bigint := 0;
begin
  if not public.is_snorky_admin() then
    raise exception 'ADMIN_REQUIRED';
  end if;

  select * into v_report
  from public.user_reports
  where id = p_report_id
  for update;
  if not found then raise exception 'REPORT_NOT_FOUND'; end if;
  if v_report.buddy_post_id is distinct from p_buddy_post_id then
    raise exception 'REPORT_POST_MISMATCH';
  end if;

  select * into v_post
  from public.buddy_posts
  where id = p_buddy_post_id
  for update;
  if not found then raise exception 'BUDDY_POST_NOT_FOUND'; end if;

  if v_post.status = 'CANCELED' then
    return jsonb_build_object(
      'report_id', p_report_id,
      'buddy_post_id', p_buddy_post_id,
      'status', 'CANCELED',
      'already_canceled', true,
      'cancelled_applications', 0
    );
  end if;

  update public.buddy_posts
  set status = 'CANCELED', updated_at = v_now
  where id = p_buddy_post_id;

  update public.buddy_applications
  set status = 'CANCELED', updated_at = v_now
  where buddy_post_id = p_buddy_post_id
    and status in ('PENDING', 'APPROVED');
  get diagnostics v_cancelled_applications = row_count;

  insert into public.buddy_post_moderation_actions (
    report_id, buddy_post_id, reason, created_at, created_by
  ) values (
    p_report_id, p_buddy_post_id, nullif(btrim(p_reason), ''), v_now, auth.uid()
  );

  insert into public.user_notifications (
    user_id, type, title, content, buddy_post_id, link_url
  ) values (
    v_post.user_id, 'buddy_post_canceled', '버디공고 취소 안내',
    '신고 검토 결과 해당 버디공고가 관리자에 의해 취소되었습니다.',
    p_buddy_post_id, './buddy.html'
  );

  if v_report.reporter_user_id is not null and v_report.reporter_user_id <> v_post.user_id then
    insert into public.user_notifications (
      user_id, type, title, content, buddy_post_id, link_url
    ) values (
      v_report.reporter_user_id, 'report_post_canceled', '신고 처리 안내',
      '신고하신 버디공고가 관리자 검토 후 취소되었습니다.',
      p_buddy_post_id, './buddy.html'
    );
  end if;

  return jsonb_build_object(
    'report_id', p_report_id,
    'buddy_post_id', p_buddy_post_id,
    'status', 'CANCELED',
    'already_canceled', false,
    'cancelled_applications', v_cancelled_applications
  );
end;
$$;

revoke all on function public.moderate_buddy_post_admin(bigint, bigint, text) from public;
grant execute on function public.moderate_buddy_post_admin(bigint, bigint, text) to authenticated, service_role;
