create table if not exists public.open_meteo_api_request_log (
  id bigint generated by default as identity primary key,
  provider text not null,
  requested_at timestamptz not null default now(),
  run_id uuid not null,
  request_kind text not null default 'batch',
  http_status integer,
  outcome text not null default 'started',
  completed_at timestamptz
);
create index if not exists open_meteo_request_log_provider_time_idx
  on public.open_meteo_api_request_log(provider,requested_at desc);
alter table public.open_meteo_api_request_log enable row level security;
revoke all on public.open_meteo_api_request_log from public,anon,authenticated;
grant select,insert,update on public.open_meteo_api_request_log to service_role;
grant usage,select on sequence public.open_meteo_api_request_log_id_seq to service_role;

create or replace function public.open_meteo_rate_limit_snapshot(p_planned integer default 0)
returns jsonb language sql stable security definer set search_path=public as $$
with logged as (
  select
    count(*) filter(where requested_at>=now()-interval '1 minute')::integer as minute_calls,
    count(*) filter(where requested_at>=now()-interval '1 hour')::integer as hour_calls,
    count(*) filter(where requested_at>=date_trunc('day',now()))::integer as day_logged
  from open_meteo_api_request_log where provider='open_meteo_marine'
), daily as (
  select coalesce(http_requests,request_count,0)::integer as day_calls,last_request_at
  from open_meteo_api_usage where provider='open_meteo_marine' and usage_date=current_date
), combined as (
  select
    logged.minute_calls + case when coalesce(daily.day_calls,0)>logged.day_logged and daily.last_request_at>=now()-interval '1 minute' then coalesce(daily.day_calls,0)-logged.day_logged else 0 end as minute_calls,
    logged.hour_calls + case when coalesce(daily.day_calls,0)>logged.day_logged and daily.last_request_at>=now()-interval '1 hour' then coalesce(daily.day_calls,0)-logged.day_logged else 0 end as hour_calls,
    greatest(logged.day_logged,coalesce(daily.day_calls,0)) as day_calls
  from logged left join daily on true
)
select jsonb_build_object(
  'callsLastMinute',minute_calls,
  'callsLastHour',hour_calls,
  'callsToday',day_calls,
  'planned',greatest(p_planned,0),
  'projectedMinute',minute_calls+greatest(p_planned,0),
  'projectedHour',hour_calls+greatest(p_planned,0),
  'projectedDay',day_calls+greatest(p_planned,0),
  'safe',(minute_calls+greatest(p_planned,0)<=600 and hour_calls+greatest(p_planned,0)<=5000 and day_calls+greatest(p_planned,0)<=10000)
) from combined
$$;
revoke all on function public.open_meteo_rate_limit_snapshot(integer) from public,anon,authenticated;
grant execute on function public.open_meteo_rate_limit_snapshot(integer) to service_role;
notify pgrst,'reload schema';
