insert into public.indoor_diving_centers (
  id, name, region, sub_region, address, max_depth, min_depth, depth_values,
  operation_status, business_hours, holiday, phone, homepage, facilities,
  feature_short, feature_full, description, pool_specs, price_short, price_full,
  rental_info, reservation_info, reservation_type, buddy_condition, buddy_rule,
  license_level, weekday_open, night_open, night_start, night_end, sat_open,
  sun_open, holiday_open, solo_allowed, min_divers, instructor_required,
  equipment_rental_status, verification_status, source_url, source_checked_at,
  entry_condition, weekday_hours, weekend_hours, reservation_required, sort_order
) values (
  'center_14',
  '아르피아 잠수풀',
  '경기',
  '용인시',
  '경기 용인시 기흥구 포은대로 499 (죽전동, 용인포은아트홀)',
  5,
  5,
  '[5.0]',
  'OPERATIONAL',
  concat_ws(E'\n', '평일 야간 운영', '주말 및 공휴일 정상 운영'),
  '주말 운영',
  '070-8818-8888',
  null,
  '주차 가능(용인 포은아트홀 연계), 샤워실 완비',
  '용인 죽전 포은아트홀(아르피아 스포츠센터) 내 위치한 수심 5m의 깔끔한 실내 잠수풀입니다.',
  '용인 죽전 포은아트홀(아르피아 스포츠센터) 내 위치한 수심 5m의 깔끔한 실내 잠수풀입니다.',
  '용인 죽전 포은아트홀(아르피아 스포츠센터) 내 위치한 수심 5m의 깔끔한 실내 잠수풀입니다. 지자체 공공 문화체육시설로 쾌적한 환경과 합리적인 요금으로 이용할 수 있습니다.',
  '실내 다이빙풀 (수심 5m, 포은아트홀 부대시설)',
  '용인 시민 및 일반 10,000원 ~ 15,000원 (공공 감면 혜택 있음)',
  '용인 시민 및 일반 10,000원 ~ 15,000원 (공공 감면 혜택 있음)',
  '일부 장비 대여 가능',
  '사전 예약 필수',
  'REQUIRED',
  '프리다이버 Lv1 이상 또는 오픈워터 이상, 버디 필수',
  'BUDDY_REQUIRED',
  'Lv1, 오픈워터',
  true, true, null, null, true, true, true, false, 2, null,
  'PAID', 'VERIFIED', null, null,
  '프리다이버 Lv1 이상 또는 오픈워터 이상, 버디 필수',
  '평일 야간 운영',
  '주말 및 공휴일 정상 운영',
  '사전 예약 필수',
  14
)
on conflict (id) do nothing;
