-- 사용자 신고 접수 저장소: submit-inquiry(service_role)에서만 신규 접수한다.
create table if not exists public.user_reports (
  id bigint generated by default as identity primary key,
  target_user_id text not null,
  target_nickname text,
  reporter_user_id text,
  reporter_nickname text,
  reason text not null,
  details text,
  buddy_post_id bigint references public.buddy_posts(id) on delete set null,
  status text not null default 'PENDING'
    check (status in ('PENDING', 'REVIEWED', 'ACTIONED', 'DISMISSED')),
  action_type text
    check (action_type is null or action_type in ('WARNING', 'SUSPEND_3_DAYS', 'SUSPEND_7_DAYS', 'SUSPEND_30_DAYS', 'PERMANENT_BAN')),
  action_reason text,
  reported_at timestamptz not null default timezone('utc'::text, now()),
  reviewed_at timestamptz,
  reviewed_by uuid
);

create index if not exists idx_user_reports_status_reported
  on public.user_reports (status, reported_at desc);
create index if not exists idx_user_reports_target
  on public.user_reports (target_user_id, reported_at desc);

alter table public.user_reports enable row level security;
revoke all on public.user_reports from anon, authenticated;
grant all on public.user_reports to service_role;
grant usage, select on sequence public.user_reports_id_seq to service_role;
