create table if not exists public.admin_user_actions (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  action_type text not null,
  action_reason text,
  created_at timestamptz not null default now(),
  created_by uuid not null default auth.uid()
);

create index if not exists admin_user_actions_user_created_idx on public.admin_user_actions(user_id, created_at desc);

create or replace function public.get_admin_users(p_search text default null)
returns table (
  user_id uuid,
  email text,
  nickname text,
  status text,
  suspended_until timestamptz,
  banned boolean,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if not exists (select 1 from public.admin_users where admin_users.user_id = auth.uid()) then
    raise exception 'ADMIN_REQUIRED';
  end if;
  return query
  select u.id, u.email, p.custom_nickname,
    case when coalesce(p.banned, false) then 'PERMANENT_BAN'
         when p.suspended_until is not null and p.suspended_until > now() then 'SUSPENDED'
         when a.action_type = 'WARNING' then 'WARNING'
         else 'ACTIVE' end,
    p.suspended_until, coalesce(p.banned, false), u.created_at
  from auth.users u
  left join public.user_profiles p on p.provider_user_id = u.id::text
  left join lateral (select aua.action_type from public.admin_user_actions aua where aua.user_id = u.id order by aua.created_at desc limit 1) a on true
  where p_search is null
     or u.id::text ilike '%' || p_search || '%'
     or coalesce(u.email, '') ilike '%' || p_search || '%'
     or coalesce(p.custom_nickname, '') ilike '%' || p_search || '%'
  order by u.created_at desc;
end;
$$;

create or replace function public.moderate_user_direct(p_user_id uuid, p_action_type text, p_action_reason text default null)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare v_until timestamptz;
begin
  if not exists (select 1 from public.admin_users where admin_users.user_id = auth.uid()) then
    raise exception 'ADMIN_REQUIRED';
  end if;
  if p_action_type not in ('WARNING','SUSPEND_3_DAYS','SUSPEND_7_DAYS','SUSPEND_30_DAYS','PERMANENT_BAN','CLEAR') then
    raise exception 'INVALID_ACTION';
  end if;
  v_until := case p_action_type when 'SUSPEND_3_DAYS' then now() + interval '3 days' when 'SUSPEND_7_DAYS' then now() + interval '7 days' when 'SUSPEND_30_DAYS' then now() + interval '30 days' else null end;
  update public.user_profiles set banned = (p_action_type = 'PERMANENT_BAN'), suspended_until = v_until, updated_at = now() where provider_user_id = p_user_id::text;
  if not found then raise exception 'USER_PROFILE_NOT_FOUND'; end if;
  insert into public.admin_user_actions(user_id, action_type, action_reason, created_by) values (p_user_id, p_action_type, p_action_reason, auth.uid());
  return jsonb_build_object('user_id', p_user_id, 'action_type', p_action_type, 'reason', p_action_reason);
end;
$$;

revoke all on function public.get_admin_users(text) from public;
revoke all on function public.moderate_user_direct(uuid, text, text) from public;
grant execute on function public.get_admin_users(text) to authenticated;
grant execute on function public.moderate_user_direct(uuid, text, text) to authenticated;
