create table if not exists public.kma_api_usage (
  provider text not null default 'KMA', api_name text not null, usage_date date not null default current_date,
  request_count integer not null default 0, success_count integer not null default 0, failure_count integer not null default 0,
  count_429 integer not null default 0, count_5xx integer not null default 0, timeout_count integer not null default 0,
  last_request_at timestamptz, last_http_status integer, updated_at timestamptz not null default now(),
  primary key(provider,api_name,usage_date)
);
alter table public.kma_weather_cache add column if not exists source_issued_at timestamptz,add column if not exists last_successful_at timestamptz,add column if not exists stale boolean not null default false,add column if not exists http_status integer;
create table if not exists public.kma_api_request_log (
  id bigint generated by default as identity primary key, provider text not null default 'KMA', api_name text not null,
  request_timestamp timestamptz not null default now(), run_id uuid not null, http_status integer, outcome text not null default 'started', completed_at timestamptz
);
create index if not exists kma_api_request_log_time_idx on public.kma_api_request_log(provider,request_timestamp desc);
alter table public.kma_api_usage enable row level security;alter table public.kma_api_request_log enable row level security;
revoke all on public.kma_api_usage,public.kma_api_request_log from public,anon,authenticated;
grant select,insert,update on public.kma_api_usage,public.kma_api_request_log to service_role;
grant usage,select on sequence public.kma_api_request_log_id_seq to service_role;

create table if not exists public.kma_safety_cache (
  id bigint generated by default as identity primary key, source_issued_at timestamptz not null,
  fetched_at timestamptz not null,last_successful_at timestamptz not null,status text not null check(status='fresh'),stale boolean not null default false,
  http_status integer not null,warning_payload jsonb not null,normalized_warnings jsonb not null,warning_index jsonb not null,created_at timestamptz not null default now(),
  unique(source_issued_at)
);
create index if not exists kma_safety_cache_latest_idx on public.kma_safety_cache(fetched_at desc) where status='fresh';
alter table public.kma_safety_cache enable row level security;revoke all on public.kma_safety_cache from public,anon,authenticated;
grant select,insert,update on public.kma_safety_cache to service_role;grant usage,select on sequence public.kma_safety_cache_id_seq to service_role;

do $$ begin if not exists(select 1 from vault.secrets where name='kma_automation_scheduler_token') then
  perform vault.create_secret(encode(extensions.gen_random_bytes(32),'hex'),'kma_automation_scheduler_token','SNORKY KMA Weather/Safety scheduler token');end if;end $$;
create or replace function public.validate_kma_automation_scheduler_token(candidate text) returns boolean language sql stable security definer set search_path=public,vault as $$
select coalesce(candidate<>'' and exists(select 1 from vault.decrypted_secrets where name='kma_automation_scheduler_token' and decrypted_secret=candidate),false)$$;
create or replace function public.kma_rate_limit_snapshot(p_api_name text,p_planned integer default 0) returns jsonb language sql stable security definer set search_path=public as $$
with c as(select count(*) filter(where request_timestamp>=now()-interval '1 minute')::integer m,count(*) filter(where request_timestamp>=now()-interval '1 hour')::integer h,count(*) filter(where request_timestamp>=date_trunc('day',now()))::integer d from kma_api_request_log where provider='KMA'), a as(select coalesce(sum(request_count),0)::integer d from kma_api_usage where provider='KMA' and usage_date=current_date)
select jsonb_build_object('minute',c.m,'hour',c.h,'today',greatest(c.d,a.d),'planned',greatest(p_planned,0),'projected',greatest(c.d,a.d)+greatest(p_planned,0),'safe',c.m+greatest(p_planned,0)<=60 and c.h+greatest(p_planned,0)<=1000 and greatest(c.d,a.d)+greatest(p_planned,0)<=3000) from c,a$$;
revoke all on function public.validate_kma_automation_scheduler_token(text) from public,anon,authenticated;
revoke all on function public.kma_rate_limit_snapshot(text,integer) from public,anon,authenticated;
grant execute on function public.validate_kma_automation_scheduler_token(text) to service_role;
grant execute on function public.kma_rate_limit_snapshot(text,integer) to service_role;
notify pgrst,'reload schema';
