create table if not exists public.kma_weather_cache (
  id bigint generated by default as identity primary key,
  grid_key text not null check (grid_key ~ '^[0-9]+:[0-9]+$'),
  nx smallint not null check (nx between 1 and 149),
  ny smallint not null check (ny between 1 and 253),
  base_date text not null check (base_date ~ '^[0-9]{8}$'),
  base_time text not null check (base_time ~ '^[0-9]{4}$'),
  forecast_data jsonb not null,
  fetched_at timestamptz not null,
  updated_at timestamptz not null default now(),
  status text not null default 'fresh' check (status in ('fresh','stale','failed')),
  response_bytes integer not null default 0 check (response_bytes >= 0),
  item_count integer not null default 0 check (item_count >= 0),
  unique (grid_key, base_date, base_time)
);

create index if not exists kma_weather_cache_latest_success_idx
  on public.kma_weather_cache (grid_key, base_date desc, base_time desc)
  where status = 'fresh';

create index if not exists kma_weather_cache_cleanup_idx
  on public.kma_weather_cache (fetched_at);

alter table public.kma_weather_cache enable row level security;
revoke all on public.kma_weather_cache from anon, authenticated;
grant select, insert, update, delete on public.kma_weather_cache to service_role;
grant usage, select on sequence public.kma_weather_cache_id_seq to service_role;

create table if not exists public.kma_refresh_lock (
  lock_name text primary key,
  owner_token uuid not null,
  acquired_at timestamptz not null default now(),
  expires_at timestamptz not null,
  updated_at timestamptz not null default now()
);

alter table public.kma_refresh_lock
  add column if not exists acquired_at timestamptz not null default now();

alter table public.kma_refresh_lock enable row level security;
revoke all on public.kma_refresh_lock from anon, authenticated;
grant select, insert, update, delete on public.kma_refresh_lock to service_role;

create or replace function public.try_acquire_kma_refresh_lock(
  p_lock_name text,
  p_owner_token uuid,
  p_ttl_seconds integer default 600
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  affected integer;
begin
  if p_ttl_seconds < 30 or p_ttl_seconds > 3600 then
    raise exception 'invalid refresh lock ttl';
  end if;
  insert into public.kma_refresh_lock (lock_name, owner_token, acquired_at, expires_at, updated_at)
  values (p_lock_name, p_owner_token, now(), now() + make_interval(secs => p_ttl_seconds), now())
  on conflict (lock_name) do update
    set owner_token = excluded.owner_token,
        acquired_at = excluded.acquired_at,
        expires_at = excluded.expires_at,
        updated_at = now()
    where public.kma_refresh_lock.expires_at <= now()
       or public.kma_refresh_lock.owner_token = excluded.owner_token;
  get diagnostics affected = row_count;
  return affected = 1;
end;
$$;

create or replace function public.release_kma_refresh_lock(
  p_lock_name text,
  p_owner_token uuid
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  affected integer;
begin
  delete from public.kma_refresh_lock
   where lock_name = p_lock_name and owner_token = p_owner_token;
  get diagnostics affected = row_count;
  return affected = 1;
end;
$$;

revoke all on function public.try_acquire_kma_refresh_lock(text, uuid, integer) from public, anon, authenticated;
revoke all on function public.release_kma_refresh_lock(text, uuid) from public, anon, authenticated;
grant execute on function public.try_acquire_kma_refresh_lock(text, uuid, integer) to service_role;
grant execute on function public.release_kma_refresh_lock(text, uuid) to service_role;

create or replace function public.cleanup_kma_weather_cache()
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  deleted_count bigint;
begin
  with latest_fresh as (
    select distinct on (grid_key) id
      from public.kma_weather_cache
     where status = 'fresh'
     order by grid_key, base_date desc, base_time desc, fetched_at desc, id desc
  ), deleted as (
    delete from public.kma_weather_cache cache
     where cache.fetched_at < now() - interval '3 days'
       and not exists (
         select 1 from latest_fresh protected where protected.id = cache.id
       )
    returning 1
  )
  select count(*) into deleted_count from deleted;
  return deleted_count;
end;
$$;

revoke all on function public.cleanup_kma_weather_cache() from public, anon, authenticated;
grant execute on function public.cleanup_kma_weather_cache() to service_role;

-- Register the independent daily cleanup only when pg_cron is already enabled.
-- The guarded block keeps this migration portable to projects without pg_cron.
do $$
begin
  if exists (select 1 from pg_extension where extname = 'pg_cron') then
    if not exists (select 1 from cron.job where jobname = 'kma-weather-cache-daily-cleanup') then
      perform cron.schedule(
        'kma-weather-cache-daily-cleanup',
        '17 18 * * *',
        'select public.cleanup_kma_weather_cache();'
      );
    end if;
  end if;
end $$;

notify pgrst, 'reload schema';
