create table if not exists public.open_meteo_marine_cache (
  id bigint generated by default as identity primary key,
  cache_key text not null,
  latitude double precision not null,
  longitude double precision not null,
  issued_at timestamptz not null,
  forecast_at timestamptz not null,
  normalized_data jsonb not null,
  source_payload_meta jsonb not null default '{}'::jsonb,
  fetched_at timestamptz not null,
  status text not null default 'fresh' check (status in ('fresh','stale','failed')),
  stale boolean not null default false,
  response_bytes integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (cache_key, issued_at, forecast_at)
);

create index if not exists open_meteo_marine_latest_idx
  on public.open_meteo_marine_cache (cache_key, issued_at desc, forecast_at);
create index if not exists open_meteo_marine_fresh_idx
  on public.open_meteo_marine_cache (cache_key, fetched_at desc)
  where status = 'fresh' and stale = false;

alter table public.open_meteo_marine_cache enable row level security;
revoke all on public.open_meteo_marine_cache from anon, authenticated;
grant select, insert, update, delete on public.open_meteo_marine_cache to service_role;
grant usage, select on sequence public.open_meteo_marine_cache_id_seq to service_role;

create table if not exists public.open_meteo_api_usage (
  id bigint generated by default as identity primary key,
  provider text not null,
  usage_date date not null default current_date,
  request_count integer not null default 0,
  batch_count integer not null default 0,
  last_request_at timestamptz,
  last_http_status integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider, usage_date)
);

alter table public.open_meteo_api_usage enable row level security;
revoke all on public.open_meteo_api_usage from anon, authenticated;
grant select, insert, update on public.open_meteo_api_usage to service_role;
grant usage, select on sequence public.open_meteo_api_usage_id_seq to service_role;

create or replace function public.cleanup_open_meteo_marine_cache()
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare deleted_count bigint;
begin
  -- Keep every forecast row belonging to the latest successful issue per key.
  with latest_issue as (
    select cache_key, max(issued_at) as issued_at
    from open_meteo_marine_cache
    where status = 'fresh'
    group by cache_key
  ), deleted as (
    delete from open_meteo_marine_cache c
    where c.fetched_at < now() - interval '7 days'
      and not exists (
        select 1 from latest_issue l
        where l.cache_key = c.cache_key and l.issued_at = c.issued_at
      )
    returning 1
  )
  select count(*) into deleted_count from deleted;
  return deleted_count;
end $$;

revoke all on function public.cleanup_open_meteo_marine_cache() from public, anon, authenticated;
grant execute on function public.cleanup_open_meteo_marine_cache() to service_role;
notify pgrst, 'reload schema';
